stages:
  - build
  - lint
  - release
  - deploy

variables:
  DOCKER_BUILD_NAME: skatekrak-build
  DOCKER_LINT_NAME: skatekrak-lint
  K8S_DEPLOYMENT_NAME: skatekrak
  K8S_CONTAINER_NAME: skatekrak
  BUILD_STAGING_BUILD_TAG: build-staging
  BUILD_PROD_BUILD_TAG: build-prod
  STAGING_TAG: staging
  STABLE_TAG: latest

.build:
  stage: build
  retry: 1
  services:
    - docker:dind
  script:
    - env | sed -n "s/^$PREFIX_VAR\(.*\)$/\1/p" > .env
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$BUILD_TAG || true
    - docker-compose -f docker-compose.ci.yml build $DOCKER_BUILD_NAME
    - docker push $CI_REGISTRY_IMAGE:$BUILD_TAG

build_feature:
  extends: .build
  variables:
    PREFIX_VAR: BUILD_STAGING_
    BUILD_STAGING_BUILD_TAG: $CI_COMMIT_REF_SLUG
  only:
    - /^feature\/.*$/
  when: manual
  allow_failure: false

build_staging:
  extends: .build
  variables:
    PREFIX_VAR: BUILD_STAGING_
  only:
    - develop

build_prod:
  extends: .build
  variables:
    PREFIX_VAR: BUILD_PROD_
  only:
    - tags

.lint:
  stage: lint
  retry: 1
  services:
    - docker:dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$BUILD_TAG
    - docker-compose -f docker-compose.ci.yml run --rm $DOCKER_LINT_NAME
  when: on_success

lint_staging:
  extends: .lint
  variables:
    BUILD_TAG: $BUILD_STAGING_BUILD_TAG
  only:
    - develop

lint_prod:
  extends: .lint
  variables:
    BUILD_TAG: $BUILD_PROD_BUILD_TAG
  only:
    - tags

.release:
  stage: release
  retry: 1
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$BUILD_TAG
  when: on_success

release_staging:
  extends: .release
  variables:
    BUILD_TAG: $BUILD_STAGING_BUILD_TAG
  script:
    - docker tag $CI_REGISTRY_IMAGE:$BUILD_TAG $CI_REGISTRY_IMAGE:$STAGING_TAG
    - docker push $CI_REGISTRY_IMAGE:$STAGING_TAG
  only:
    - develop

release_prod:
  extends: .release
  variables:
    BUILD_TAG: $BUILD_PROD_BUILD_TAG
  script:
    - docker tag $CI_REGISTRY_IMAGE:$BUILD_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$BUILD_TAG $CI_REGISTRY_IMAGE:$STABLE_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$STABLE_TAG
  only:
    - tags

.deploy:
  stage: deploy
  script:
    - |
      if kubectl set image deployment/$K8S_DEPLOYMENT_NAME $K8S_CONTAINER_NAME=$CI_REGISTRY_IMAGE:$DEPLOY_TAG | grep -q updated; then
          echo "=> Deployment has set a new image, no need to force update"
      else
          echo "=> Patching Deployment to force update"
          kubectl patch deployment/$K8S_DEPLOYMENT_NAME -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      fi
    - kubectl rollout status deployment/$K8S_DEPLOYMENT_NAME
    - kubectl describe deployment $K8S_DEPLOYMENT_NAME

deploy_feature:
  extends: .deploy
  tags:
    - do-k8s-staging
  variables:
    DEPLOY_TAG: $CI_COMMIT_REF_SLUG
  environment:
    name: staging
    url: "https://staging.skatekrak.com"
  only:
    - /^feature\/.*$/
  when: on_success

deploy_staging:
  extends: .deploy
  tags:
    - do-k8s-staging
  variables:
    DEPLOY_TAG: $STAGING_TAG
  environment:
    name: staging
    url: "https://staging.skatekrak.com"
  only:
    - develop
  when: on_success

deploy_prod:
  extends: .deploy
  tags:
    - do-k8s-prod
  variables:
    DEPLOY_TAG: $CI_COMMIT_TAG
  environment:
    name: production
    url: "https://skatekrak.com"
  only:
    - tags
  when: manual
