stages:
    - build
    - deploy

before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN hub.skatekrak.com

variables:
    HUB_URL: "hub.skatekrak.com/web/skatekrak.com"
    TAG: ":latest"

build:
    stage: build
    tags:
        - docker
    image: docker:latest
    script:
        - docker info
        - docker build -t $HUB_URL .
        - docker push $HUB_URL$TAG
    only:
        - master

deploy:
    stage: deploy
    tags:
        - deploy
    variables:
        FOLDER_DEPLOY: "/docker/skatekrak"
        NAME: "skatekrak"
    script:
        - mkdir -p $FOLDER_DEPLOY
        - cp docker-compose.yml $FOLDER_DEPLOY
        - cd /docker
        - docker run -t --rm -v /var/local/lib/docker:/docker sushifu/compose-merger
        - docker-compose stop $NAME
        - docker-compose rm -f $NAME
        - docker pull $HUB_URL$TAG
        - docker-compose up -d $NAME
        - docker images -q | xargs docker rmi || true
    only:
        - master