stages:
    - build
    - release
    - deploy
variables:
    HUB_URL: hub.skatekrak.com/web/skatekrak.com
    HUB_PROD: gcr.io/krakbackend/homepage
    TEST_TAG: testing
before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN hub.skatekrak.com
build:
    stage: build
    script:
        - 'docker build --pull -t $HUB_URL:$TEST_TAG .'
        - 'docker push $HUB_URL:$TEST_TAG'
    only:
        - tags
release_prod:
    stage: release
    tags:
        - kube
    script:
        - 'docker pull $HUB_URL:$TEST_TAG'
        - 'docker tag $HUB_URL:$TEST_TAG $HUB_PROD:$CI_COMMIT_TAG'
        - 'gcloud docker -- push $HUB_PROD:$CI_COMMIT_TAG'
    only:
        - tags
    when: on_success
deploy_prod:
    stage: deploy
    tags:
        - kube
    environment:
        name: production
        url: 'https://skatekrak.com'
    script:
        - >-
            kubectl set image deployment/homepage
            homepage=$HUB_PROD:$CI_COMMIT_TAG
        - kubectl rollout status deployment/homepage
        - kubectl describe deployment homepage
    only:
        - tags
    when: on_success
