stages:
    - build
    - release
    - deploy

variables:
    HUB_URL: "hub.skatekrak.com/web/skatekrak.com"

before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN hub.skatekrak.com

build:
    stage: build
    script:
        - docker build -t $HUB_URL:testing .
        - docker push $HUB_URL:testing
    only:
        - tags

release:
    stage: release
    script:
        - docker pull $HUB_URL:testing
        - docker tag $HUB_URL:testing $HUB_URL:latest
        - docker push $HUB_URL:latest
    only:
        - tags
    when: on_success

deploy:
    stage: deploy
    tags:
        - deploy
    script:
        - docker-compose pull
        - docker-compose up -d --force-recreate
    only:
        - tags
    when: on_success
