version: "3"
services:
  skatekrak-build:
    image: ${CI_REGISTRY_IMAGE}:${TEST_TAG}
    build:
      context: .
      args:
        NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
      cache_from:
        - ${CI_REGISTRY_IMAGE}:${TEST_TAG}

  skatekrak-lint:
    image: ${CI_REGISTRY_IMAGE}:${TEST_TAG}
    command: /bin/bash -c "yarn install && yarn lint"
