version: "3"
services:
  oauth2:
    restart: always
    image: "a5huynh/oauth2_proxy:latest"
    command:
      --cookie-secure=true --upstream="http://skatekrak-staging:3000"
      --http-address="0.0.0.0:4180"
      --redirect-url="https://home.staging.skatekrak.com/oauth2/callback"
      --email-domain="skatekrak.com" --custom-templates-dir="/templates"
    volumes:
      - "/docker/Krak-OAuth2-Proxy/templates:/templates:ro"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=skatekrak-staging
      - "traefik.frontend.rule=Host:home.staging.skatekrak.com"
      - traefik.port=4180
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=rCy27mkCr9mfc9K8GVC3BeNuJ477W6
      - OAUTH2_PROXY_COOKIE_DOMAIN=staging.skatekrak.com
      - >-
        OAUTH2_PROXY_CLIENT_ID=932345581894-dmi6cjkejtb4i6hs32h54kulhtu95g8n.apps.googleusercontent.com
      - OAUTH2_PROXY_CLIENT_SECRET=ccLfreERpYpCC4-dEkzOkqen
    networks:
      - web

  skatekrak-staging:
    image: "$CI_REGISTRY_IMAGE:$STAGING_TAG"
    restart: always
    depends_on:
      - oauth2
    networks:
      - web

networks:
  web:
    external: true
