version: "3.4"
services:
  skatekrak-build:
    image: ${CI_REGISTRY_IMAGE}:${BUILD_TAG}
    build:
      context: .
      args:
        - NPM_AUTH_TOKEN
        - BEARER
        - STRIPE_KEY
        - CAIROTE_URL
        - SESTERCES_URL
        - RSS_BACKEND_URL
        - INTERCOM_ID
        - CACHING_URL
        - REDIRECT_URL
        - RENEW_DATE
        - RENEW_DATE_QUARTERFULL
      cache_from:
        - ${CI_REGISTRY_IMAGE}:${BUILD_TAG}

  skatekrak-lint:
    image: ${CI_REGISTRY_IMAGE}:${BUILD_TAG}
    command: /bin/bash -c "yarn install && yarn build:ts && yarn lint:ts"
