version: "3"
services:
  skatekrak:
    image: node:lts
    command: bash -c "yarn install && yarn start:cmd:dev"
    working_dir: /app
    networks:
      - web
    ports:
      - 9233:9230
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=skatekrak
      - traefik.frontend.rule=Host:dev.skatekrak.com
      - traefik.port=3000
    env_file: .env
    volumes:
      - ./:/app:delegated
      - ~/.npmrc:/app/.npmrc:ro
      - skatekrak-next:/app/.next
      - skatekrak-node_modules:/app/node_modules

networks:
  web:
    external: true

volumes:
  skatekrak-next: null
  skatekrak-node_modules: null
