version: "3"
services:
  skatekrak:
    image: node:lts
    command: bash -c "yarn install && yarn start:cmd:dev"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=skatekrak
      - traefik.frontend.rule=Host:dev.skatekrak.com
      - traefik.port=3000
    working_dir: /app
    volumes:
      - .:/app
      - ~/.npmrc:/app/.npmrc:ro
      - skatekrak-next:/app/.next
      - skatekrak-node_modules:/app/node_modules
    env_file: .env

volumes:
  skatekrak-next: null
  skatekrak-node_modules: null

networks:
  web:
    external: true
