services:
    web:
        image: oven/bun:1.2.21
        command: bash -c "bun install && bun dev:web"
        labels:
            - traefik.enable=true
            - traefik.http.routers.skatekrak.entrypoints=http,https
            - traefik.http.routers.skatekrak.rule=Host(`dev.skatekrak.com`) # You can use any domain allowed by your TLS certificate
            - traefik.http.routers.skatekrak.tls=true
            - traefik.http.routers.skatekrak.service=skatekrak
            - traefik.http.services.skatekrak.loadbalancer.server.port=3000 # Adapt to the exposed port in the service

        # - traefik.http.routers.skatekrak.middlewares=carrelage-redir
        # - traefik.http.middlewares.carrelage-redir.redirectregex.regex=Ë†https://api.dev.skatekrak.com/(.*)
        # - traefik.http.middlewares.carrelage-redir.redirectregex.replacement=http://carrelage-carrelage-1:3636/$$1
        working_dir: /app
        volumes:
            - .:/app
            - ~/.npmrc:/app/.npmrc:ro
            - skatekrak-next:/app/.next
            - skatekrak-node_modules:/app/node_modules
        env_file: apps/web/.env

    api:
        image: oven/bun:1.2.21
        command: bash -c "bun install && bun dev:api"
        labels:
            - traefik.enable=true
            - traefik.http.routers.krak-api.entrypoints=http,https
            - traefik.http.routers.krak-api.rule=Host(`api.dev.skatekrak.com`) # You can use any domain allowed by your TLS certificate
            - traefik.http.routers.krak-api.tls=true
            - traefik.http.routers.krak-api.service=krak-api
            - traefik.http.services.krak-api.loadbalancer.server.port=3000 # Adapt to the exposed port in the service
        working_dir: /app
        volumes:
            - .:/app
            - ~/.npmrc:/app/.npmrc:ro
            - skatekrak-api-node_modules:/app/node_modules
        env_file: apps/api/.env

    mongodb:
        image: mongo:7.0
        volumes:
            - ./backup:/backup
            - mongo-data:/data/db
        ports:
            - 27017:27017

    carrelage:
        image: oven/bun:1.1.7
        command: bash -c "bun install && bun dev:carrelage"
        depends_on:
            - mongodb
        labels:
            - traefik.enable=true
            - traefik.http.routers.carrelage.entrypoints=http,https
            - traefik.http.routers.carrelage.rule=Host(`carrelage.dev.skatekrak.com`)
            - traefik.http.routers.carrelage.tls=true
            - traefik.http.routers.carrelage.service=carrelage
            - traefik.http.services.carrelage.loadbalancer.server.port=3636
        working_dir: /app
        volumes:
            - .:/app
            - ~/.npmrc:/app/.npmrc:ro
            - carrelage-build:/dist
            - carrelage-node_modules:/app/node_modules
        env_file: apps/carrelage/.env
        ports:
            - 3636

volumes:
    skatekrak-next: null
    skatekrak-node_modules: null
    skatekrak-api-node_modules: null
    carrelage-build: null
    carrelage-node_modules: null
    mongo-data: null

networks:
    default:
        name: docker
        external: true
