name: skatekrak
services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: krak
            POSTGRES_PASSWORD: krak
            POSTGRES_DB: krak
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5433:5432

    meilisearch:
        image: getmeili/meilisearch:v1.13
        environment:
            MEILI_MASTER_KEY: masterKey
            MEILI_ENV: development
        volumes:
            - meilisearch-data:/meili_data
        ports:
            - 7700:7700

volumes:
    postgres-data:
    meilisearch-data:
