version: "3"
services:
  skatekrak:
    image: node:lts
    command: bash -c "yarn install && yarn start:cmd:dev"
    working_dir: /app
    networks:
      - web
    ports:
      - 9230:9230
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=skatekrak
      - traefik.frontend.rule=Host:dev.skatekrak.com
      - traefik.port=3000
    environment:
      - BEARER
      - STRIPE_KEY
      - CAIROTE_URL
      - SESTERCES_URL
      - RSS_BACKEND_URL
      - INTERCOM_ID
      - CACHING_URL
      - REDIRECT_URL
      - RENEW_DATE
      - RENEW_DATE_QUARTERFULL
    volumes:
      - ~/.npmrc:/app/.npmrc:ro
      - ./:/app:delegated

networks:
  web:
    external: true
