version: "3"
services:
  skatekrak:
    image: node:lts
    command: yarn --inspect=0.0.0.0:9229 dev
    working_dir: /app
    networks:
      - web
    ports:
      - 9229:9229
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=skatekrak
      - traefik.frontend.rule=Host:skatekrak.local.test
      - traefik.port=3000
    volumes:
      - ".:/app:delegated"

networks:
  web:
    external: true
