version: "3.4"
services:
  skatekrak-build:
    image: ${CI_REGISTRY_IMAGE}:${BUILD_TAG}
    build:
      context: .
      args:
        - NPM_AUTH_TOKEN
      cache_from:
        - ${CI_REGISTRY_IMAGE}:${BUILD_TAG}
