version: '3'
services:
    skatekrak:
        image: node:lts
        command: bash -c "yarn install && yarn start:cmd:dev"
        labels:
            - traefik.enable=true
            - traefik.http.routers.skatekrak.entrypoints=http,https
            - traefik.http.routers.skatekrak.rule=Host(`dev.skatekrak.com`) # You can use any domain allowed by your TLS certificate
            - traefik.http.routers.skatekrak.tls=true
            - traefik.http.routers.skatekrak.service=skatekrak
            - traefik.http.services.skatekrak.loadbalancer.server.port=3000 # Adapt to the exposed port in the service
            - traefik.http.routers.skatekrak.middlewares=carrelage-redir

            - traefik.http.middlewares.carrelage-redir.redirectregex.regex=Ë†https://api.dev.skatekrak.com/(.*)
            - traefik.http.middlewares.carrelage-redir.redirectregex.replacement=http://carrelage-carrelage-1:3636/$$1
        working_dir: /app
        volumes:
            - .:/app
            - skatekrak-next:/app/.next
            - skatekrak-node_modules:/app/node_modules
        env_file: .env

volumes:
    skatekrak-next: null
    skatekrak-node_modules: null

networks:
    default:
        external:
            name: docker
