[providers.age]
type = "age"
recipients = [
    "age1jckwxym4eczhfrsqrc676t9ehjqgen8et8r00fqvqnx2777vtgvsgh927y",
    "age1kumqydvw03uj29y0f3ume87g0k7mks0kcstu07ewz6fc0zhtjssqs9e9xl",
]

[secrets]
DATABASE_URL = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NG93QmVHeDlxYnN6dzZmRkJ0ZXUvejU2Nyt2MEhLQmV4Mno4UDNDTzI4CmdiaGpES0NGQXdWTjBnN2hYSUxHUG96Q2RTN0JFUGhRWEN1VFdRUFIzRkkKLT4gWDI1NTE5IG1MMUF2V29lRFVuMXB2aDZKaDVyY3F6SU42aVBWbFRPb3N4aVpXNGFQMFUKUFVyZ2ZYZjlqc0hHejRxbUYyem1EY0J4VXMxQ09xVFJydEFJSVdTZ0RRcwotPiAyKDYtZ3JlYXNlIEE0T2NsXgpDdXNrUlF6dnllSUlvcUhCb1U1NEFtVXZQYjRKMTU0dwotLS0gRnQ2dStCNHhyWkhRSGVBSjA3QjVERjcvL2RtVW9ZejFnaTdwOE9TSWd4awq8Wuv474Ye4Kj8OdrTqKDa2Z7uc+4c7JXJXaS6LLP1g2iIU3gIcFn0U9wtY7WHraeX25Sezz+++feOlvecLXarUNmNYEiXddoICg==" }
