version: '3'
services:
    mongodb:
        image: mongo:7.0
        volumes:
            - ./backup:/backup
            - mongo-data:/data/db
        ports:
            - 27017:27017

    carrelage:
        image: node:16
        command: bash -c "yarn install && yarn start:cmd:dev"
        depends_on:
            - mongodb
        labels:
            - traefik.enable=true
            - traefik.http.routers.carrelage.entrypoints=http,https
            - traefik.http.routers.carrelage.rule=Host(`api.dev.skatekrak.com`)
            - traefik.http.routers.carrelage.tls=true
            - traefik.http.routers.carrelage.service=carrelage
            - traefik.http.services.carrelage.loadbalancer.server.port=3636
        working_dir: /app
        volumes:
            - .:/app
            - ~/.npmrc:/app/.npmrc:ro
            - carrelage-build:/dist
            - carrelage-node_modules:/app/node_modules
        env_file: .env
        ports:
            - 3636

volumes:
    mongo-data: null
    carrelage-build: null
    carrelage-node_modules: null

networks:
    default:
        external:
            name: docker
