# fly.toml app configuration file generated for carrelage on 2024-01-16T21:50:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "carrelage"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3636
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
