name: Delete Custom Map
on:
    workflow_dispatch:
        inputs:
            tag:
                description: Tag the map to delete
                required: true
                type: string

env:
    NEXT_PUBLIC_BUGSNAG_KEY: ${{ secrets.NEXT_PUBLIC_BUGSNAG_KEY }}

jobs:
    create_map:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.REPO_PAT }}
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.6
            - name: Delete map data
              run: |
                  bun ./scripts/delete_map.js \
                    --tag ${{ inputs.tag }} \
            - name: Write commit
              uses: EndBug/add-and-commit@v9
              with:
                  add: "['./apps/api/src/data/customMaps/_spots.json']"
                  default_author: user_info
                  message: 'feat: Map deleted'
            - run: bun install --frozen-lockfile
            - run: bun lint
            - name: Deploying to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-args: --prod
