name: Delete Custom Map
on:
    workflow_dispatch:
        inputs:
            tag:
                description: Tag the map to delete
                required: true
                type: string

env:
    NEXT_PUBLIC_BUGSNAG_KEY: ${{ secrets.NEXT_PUBLIC_BUGSNAG_KEY }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
    create_map:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.6
            - name: Delete map data
              run: |
                  bun ./scripts/delete_map.js \
                    --tag ${{ inputs.tag }} \
            - name: Write commit
              uses: EndBug/add-and-commit@v9
              with:
                  add: "['./apps/api/src/data/customMaps/_spots.json']"
                  default_author: github_actor
                  message: 'feat: Map deleted'
            - run: bun install --frozen-lockfile
            - run: bun lint
            - name: Install Vercel CLI
              run: bun add --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
