name: Deploy

on:
    push:
        branches: [main]

env:
    NEXT_PUBLIC_BUGSNAG_KEY: ${{ secrets.NEXT_PUBLIC_BUGSNAG_KEY }}

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.10
            - run: bun install --frozen-lockfile
            - run: bun lint

    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.10
            - run: bun install --frozen-lockfile
            - run: bun run format:check

    build:
        runs-on: ubuntu-latest
        needs: [lint, format]
        env:
            NEXT_PUBLIC_CARRELAGE_URL: http://placeholder
            NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: http://placeholder
            NEXT_PUBLIC_KRAK_API_URL: http://placeholder
            NEXT_PUBLIC_STAGE: http://placeholder
            NEXT_PUBLIC_MEILI_HOST: http://placeholder
            NEXT_PUBLIC_MEILI_API_KEY: http://placeholder
            NEXT_PUBLIC_IMGPROXY_URL: http://placeholder
            NEXT_PUBLIC_UMAMI_SCRIPT_URL: http://placeholder
            NEXT_PUBLIC_UMAMI_WEBSITE_ID: http://placeholder
            NEXT_PUBLIC_WEBSITE_URL: http://placeholder
            NEXT_PUBLIC_RSS_BACKEND_URL: http://placeholder
            NEXT_PUBLIC_KRAKMAG_URL: http://placeholder
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.10
            - run: bun install --frozen-lockfile
            - run: bun run build

    deploy-api:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Trigger Dokploy deployment for API
              run: |
                  curl -X POST -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" -H "Content-Type: application/json" -H "Accept: application/json" "${{ secrets.DOKPLOY_DEPLOY_URL }}" -d '{"applicationId": "${{ secrets.DOKPLOY_API_ID }}"}'

    deploy-web:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Trigger Dokploy deployment for Web
              run: |
                  curl -X POST -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" -H "Content-Type: application/json" -H "Accept: application/json" "${{ secrets.DOKPLOY_DEPLOY_URL }}" -d '{"applicationId": "${{ secrets.DOKPLOY_WEB_ID }}"}'

    deploy-manager:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Trigger Dokploy deployment for Manager
              run: |
                  curl -X POST -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" -H "Content-Type: application/json" -H "Accept: application/json" "${{ secrets.DOKPLOY_DEPLOY_URL }}" -d '{"applicationId": "${{ secrets.DOKPLOY_MANAGER_ID }}"}'
