name: Deploy

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    NEXT_PUBLIC_BUGSNAG_KEY: ${{ secrets.NEXT_PUBLIC_BUGSNAG_KEY }}

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.6
            - run: bun install --frozen-lockfile
            - run: bun lint

    deploy_vercel:
        name: deploy web vercel
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - uses: actions/checkout@v4
            - uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-args: '--prod'
                  vercel-scope: ${{ secrets.VERCEL_SCOPE }}
              timeout-minutes: 6

    deploy_api_fly:
        name: deploy api fly
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - uses: actions/checkout@v2
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --config apps/api/fly.toml --dockerfile apps/api/Dockerfile
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    # deploy_carrelage_fly:
    #     name: deploy carrelage fly
    #     runs-on: ubuntu-latest
    #     needs: [lint]
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: superfly/flyctl-actions/setup-flyctl@master
    #         - run: flyctl deploy --remote-only --config apps/carrelage/fly.toml --dockerfile apps/carrelage/Dockerfile
    #           env:
    #               FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
